# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c17126771c8b1701f9153eae0a641c97a8db637a629bdc64a179f4c89cf569a2bcf1ae50b7992dbbe8a06ca7309ec9dec83f9bc2d84767247680fb9bc328f79

test:
  secret_key_base: 05135604bbf9617020b16400bcac604b79e4dc5a3eeb3dc9e8cfe473b515a43dd5283875e92fe412602deb77fc6bb6b92251b4e63a9afa3eecb76683a2006066

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
